### ISSUE TITLE
div(), multi() 함수작성

### ISSUE THREAD

**Issue by overall1** [overall1/calculator#2]
div(), multi()를 작성바랍니다.
----------------
add(int a, int b) 를 작성하는 것이 좋겠습니다.

**Comment by kychoi1** [comment]
알겠습니다. 오늘 중으로 완료 예정

**Comment by overall1** [comment]
add와 sub는 kimbw님이 하시기로 했으니, 
div(), multi()를 작성 요청드립니다.

**Comment by kimbw** [comment]
예... 오늘 중으로 끝내겠습니다

**Comment by kimbw** [comment]
add() 및 sub() 함수를 작성하여 feature/...skeleton 에 push 완료했습니다
